version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/saucedemoapp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
