version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Node packages
      - npm install
  build:
    commands:
      - echo Running the linter
      - npm run test.lint